name = "KleinbergBurstDetection"
uuid = "cb45a5de-a23e-40b1-9452-9619139bcc89"
authors = ["Roman Ventzke"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
